sudo: required
dist: xenial
language: cpp
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libgmp-dev libpcre2-dev -y
  - mkdir -p gmpxx pcre2
  - sh prepare.sh
script: 
  - ./autogen.sh
  - ./configure
  - make
  - make test

