sudo: required
dist: trusty
language: cpp
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 -y
  - CXX=g++-5
  - sh prepare.sh
script: 
  - ./autogen.sh
  - ./configure --enable-static --disable-shared --enable-cxx --enable-jit
  - make
  - make checkrnm

