sudo: required
dist: trusty
language: cpp
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 -y
  - CXX=g++-5
  - sudo apt-get install lzip
  - mkdir -p gmpxx
  - wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz
  - tar --lzip -vxf gmp-6.1.2.tar.lz --strip-components=1 -C gmpxx
  - rm -rf pcre2
  - git clone https://github.com/jpcre2/pcre2
  - wget https://raw.githubusercontent.com/Amerge/icu/master/icu4c-58_2-src.tgz
  - tar -vxf icu4c-58_2-src.tgz
  - mv -f icu/source/* icu
script: 
  - ./configure --enable-static --disable-shared --enable-cxx
  - make
  - make checkrnm

