#!/bin/sh
file="$1"
if [ -z "$file" ]; then
	file=doxy/doxydoc.md
fi
mv -f README.md README.md.bak
sed -e 's@^\(.*\)[[:blank:]]*{#\([^}]*\)}[[:blank:]]*$@<a name="\2"></a>\n\n\1@' "$file" > README.md
